global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'

route:
  receiver: 'email-alerts'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'contact@alidabo.site'
        from: 'contact@alidabo.site'
        smarthost: 'smtp.alidabo.site:587'
        auth_username: 'contact@alidabo.site'
        auth_identity: 'contact@alidabo.site'
        auth_password: 'AlsonDab2313@'
        require_tls: true

  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/webhook'

  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

templates:
  - '/etc/alertmanager/template/*.tmpl' 