global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'

route:
  receiver: 'email-alerts'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'email-alerts'
    email_configs:
      # REMPLACEZ PAR VOS VRAIS IDENTIFIANTS GMAIL :
      # 1. Allez sur https://myaccount.google.com/
      # 2. Sécurité → Authentification à 2 facteurs → Activer
      # 3. Mots de passe d'application → Générer pour "Mail"
      # 4. Remplacez les valeurs ci-dessous :
      - to: 'VOTRE_EMAIL@gmail.com'  # ← REMPLACEZ
        from: 'VOTRE_EMAIL@gmail.com'  # ← REMPLACEZ
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'VOTRE_EMAIL@gmail.com'  # ← REMPLACEZ
        auth_password: 'VOTRE_MOT_DE_PASSE_APP'  # ← REMPLACEZ (16 caractères)
        require_tls: true

  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/webhook'

  - name: 'slack-notifications'
    slack_configs:
      - channel: '#alerts'
        title: '{{ template "slack.title" . }}'
        text: '{{ template "slack.text" . }}'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

templates:
  - '/etc/alertmanager/template/*.tmpl' 