groups:
  - name: web-app-alerts
    rules:
      # High error rate alert
      - alert: HighErrorRate
        expr: rate(endpoint_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }} errors per second for the last 5 minutes"

      # High response time alert
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(endpoint_latency_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is {{ $value }} seconds"

      # Service down alert
      - alert: ServiceDown
        expr: up{job="flask_app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Web application is down"
          description: "The Flask application has been down for more than 1 minute"

      # High memory usage alert
      - alert: HighMemoryUsage
        expr: memory_usage_bytes / 1024 / 1024 > 400
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }} MB"

      # High CPU usage alert
      - alert: HighCPUUsage
        expr: cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      # Database connection issues
      - alert: DatabaseConnectionIssues
        expr: database_connections < 5
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Low database connections"
          description: "Only {{ $value }} database connections available"

      # High request rate alert
      - alert: HighRequestRate
        expr: rate(endpoint_clicks_total[5m]) > 100
        for: 2m
        labels:
          severity: info
        annotations:
          summary: "High request rate"
          description: "Request rate is {{ $value }} requests per second" 